language: scala

scala:
  - 2.12.8

jdk:
  - openjdk8

script:
  - sbt coverage test coverageReport coverageAggregate

after_success:
  - sbt coveralls codacyCoverage

notifications:
  email:
    - zhong.lunfu@gmail.com